name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps & package
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[docs]
      - name: Build docs
        run: >
          python -m pdoc
          -o ./docs
          --math
          --favicon https://raw.githubusercontent.com/rmnldwg/lyscripts/main/favicon.png
          ./lyscripts
      - name: Deploy docs to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
